"""Private native boundary; public imports live at the package root."""

REGEX_DIALECT_VERSION: str
UNICODE_VERSION: str

class LanguageSyntaxError(ValueError): ...
class LanguageWireError(ValueError): ...

class LanguageResourceError(RuntimeError):
    resource: str
    limit: int

class Limits:
    def __init__(
        self,
        max_input_bytes: int,
        max_nesting: int,
        max_nfa_states: int,
        max_states: int,
        max_transitions: int,
        max_work: int,
    ) -> None: ...

class Dfa:
    @staticmethod
    def compile(
        pattern: str,
        flags: tuple[bool, bool, bool, bool, bool, bool, bool],
        limits: Limits,
    ) -> Dfa: ...
    @staticmethod
    def literal(text: str, kind: str, limits: Limits) -> Dfa: ...
    @staticmethod
    def empty(limits: Limits) -> Dfa: ...
    @staticmethod
    def universal(limits: Limits) -> Dfa: ...
    @staticmethod
    def from_json(data: bytes, limits: Limits) -> Dfa: ...
    def accepts(self, text: str, limits: Limits) -> bool: ...
    def intersection(self, other: Dfa, limits: Limits) -> Dfa: ...
    def union(self, other: Dfa, limits: Limits) -> Dfa: ...
    def difference(self, other: Dfa, limits: Limits) -> Dfa: ...
    def complement(self, limits: Limits) -> Dfa: ...
    def is_empty(self, limits: Limits) -> bool: ...
    def witness(self, limits: Limits) -> str | None: ...
    def cardinality(self, bound: int, limits: Limits) -> int: ...
    def canonical_json(self, limits: Limits) -> bytes: ...
